# Generated by Django 3.2.4 on 2021-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
