# Generated by Django 3.2.4 on 2021-07-01 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210701_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 1, 8, 17, 41, 941866, tzinfo=utc)),
        ),
    ]
