# Generated by Django 3.2.4 on 2021-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField(max_length=10)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
